export enum ENUM_CPU_MARKET_STATUS {
  ANNOUNCED = "ANNOUNCED",
  DISCONTINUED = "DISCONTINUED",
  LAUNCHED = "LAUNCHED",
  UNKNOWN = "UNKNOWN",
}

export enum ENUM_CPU_VERTICAL_SEGMENT {
  DESKTOP = "DESKTOP",
  EMBEDDED = "EMBEDDED",
  MOBILE = "MOBILE",
  SERVER = "SERVER",
  WORKSTATION = "WORKSTATION",
  UNKNOWN = "UNKNOWN",
}
