import { ENUM_PAGINATION_ORDER_DIRECTION_TYPE } from "./pagination.enum.constant";

export const PAGINATION_AVAILABLE_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE[] =
  Object.values(ENUM_PAGINATION_ORDER_DIRECTION_TYPE);
